data_folder: "data"
analysis_2d_jobs_subfolder: "jobs"
working_dir: "."
database_file: "model.db"
# TODO: CHANGE TO A STRONG PASSWORD. VERY IMPORTANT!
secret_key: "KEEP THIS SAVE AND CHANGE IT PLEASE"
database_uri: 'postgresql:///mocap'

postgresql:
  database_url: "postgresql:///mocap"
  username: "user"
  # TODO: CHANGE TO A STRONG PASSWORD. VERY IMPORTANT!
  password: "CHANGETHIS"

openpose:
  # TODO: CHANGE THIS TO YOUR INSTALLATION_DIR
  installation_dir: "/Users/jannis/Nextcloud/Dokumente/Hochschule/Semester_5/software/openpose"
  # todo: Machen
  python_executable_path: ""
3d-pose-baseline:
  # TODO: CHANGE THIS TO YOUR INSTALLATION_DIR
  installation_dir: "../3d-pose-baseline/"
  # todo: Machen
  python_executable_path: ""