data_folder: "data"
analysis_2d_jobs_subfolder: "jobs"
working_dir: "."
database_file: "model.db"

openpose:
  # TODO: CHANGE THIS TO YOUR INSTALLATION_DIR
  installation_dir: "../openpose/"
  # todo: Machen
  python_executable_path: ""
3d-pose-baseline:
  # TODO: CHANGE THIS TO YOUR INSTALLATION_DIR
  installation_dir: "../3d-pose-baseline/"
  # todo: Machen
  python_executable_path: ""